name: Your Workflow Name
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Adjust permissions and Set safe directory
      run: |
        sudo chown -R $(whoami) /github/workspace
        git config --global --add safe.directory /github/workspace

    - name: Run youyo/sync-up-to-codecommit-action
      uses: youyo/sync-up-to-codecommit-action@v1
      with:
        repository_name: test_repo_jaime
        aws_region: us-east-1
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: AKIAQNPRQ7QQDGUH26DA
        AWS_SECRET_ACCESS_KEY: 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
