name: sync up to codecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: work around permission issue
        run: git config --global --add safe.directory
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAQNPRQ7QQDGUH26DA
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Sync up to CodeCommit
        uses: youyo/sync-up-to-codecommit-action@v1
        with:
          repository_name: test_repo_jaime
          aws_region: us-east-1
